name: test to main sync

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://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@github.com/milliwonkim/vue3-composition-api-example.git"
        source_branch: 'test'
        destination_branch: 'main'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: yarn build
        start: yarn start
